services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: []
    environment:
      TOKEN: # MTAwMTAwODgxODY4OTQyNTQwOQ.GX8tJE.Uf2o9UTgWxzf1KUebdovO9Y7e36h2fqD-lfkEo
      
